### ISSUE TITLE
Je houdt geen rekening met speciale karakters :) probeer support hiervoor toe te voegen

### ISSUE THREAD

**Issue by GekkeBoyJeff** [SafouaneM/Safouane.GG#1]
https://github.com/SafouaneM/Safouane.GG/blob/5965898c7813b5da8031df17b839b41a3b17d798/models/fetch/fetchSummoner.js#L8

**Comment by SafouaneM** [comment]
Top ik was dit helemaal vergeten :)

**Comment by SafouaneM** [comment]
Thanks I've fixed the issue check the commit
